using System.Collections;
using System.Reflection;
using System.Runtime.Loader;
using System.Text;
using System.Text.Json;

var options = Options.Parse(args);
var assemblyFullPath = Path.GetFullPath(options.AssemblyPath);
var outputFullPath = Path.GetFullPath(options.OutputPath);
var extraIds = ReadJson<Dictionary<string, int>>(options.ExtraMessageIdsPath) ?? new Dictionary<string, int>();
var routes = ReadJson<List<RouteDefinition>>(options.RoutesPath) ?? new List<RouteDefinition>();

var loadContext = new ContractLoadContext(assemblyFullPath);
var assembly = loadContext.LoadFromAssemblyPath(assemblyFullPath);

var loadableTypes = GetLoadableTypes(assembly);

var protoTypes = loadableTypes
    .Where(IsProtoContract)
    .Where(type => !type.IsEnum)
    .Where(type => type.FullName?.StartsWith("Google.Protobuf.", StringComparison.Ordinal) != true)
    .OrderBy(GetTypeScriptName, StringComparer.Ordinal)
    .ToList();

var protoTypeNames = protoTypes.ToDictionary(type => GetTypeScriptName(type), type => type, StringComparer.Ordinal);
var protoRuntimeNames = protoTypes
    .SelectMany(type => GetRuntimeNames(type).Select(name => (name, type)))
    .GroupBy(entry => entry.name, StringComparer.Ordinal)
    .ToDictionary(group => group.Key, group => group.First().type, StringComparer.Ordinal);

var enums = loadableTypes
    .Where(IsProtoContract)
    .Where(type => type.IsEnum)
    .Where(type => type.FullName?.StartsWith("Google.Protobuf.", StringComparison.Ordinal) != true)
    .OrderBy(GetTypeScriptName, StringComparer.Ordinal)
    .ToList();

var messages = ReadMessageIds(enums);
foreach (var (name, value) in extraIds)
{
    messages[name] = value;
}

ValidateRoutes(routes, messages, protoRuntimeNames);

var builder = new StringBuilder();
builder.AppendLine("// <auto-generated>");
builder.AppendLine("// Generated by GC/570/tools/generate-dota-contracts.ps1.");
builder.AppendLine("// Source inputs: server protobuf contracts, contracts/extra-message-ids.json, contracts/routes.json.");
builder.AppendLine("// Do not edit this file directly.");
builder.AppendLine("// </auto-generated>");
builder.AppendLine();
builder.AppendLine("export interface ProtoDescriptor<TMessage> {");
builder.AppendLine("    readonly name: string;");
builder.AppendLine("}");
builder.AppendLine();
builder.AppendLine("export interface GcRoute<TRequest, TResponse> {");
builder.AppendLine("    readonly requestId: number;");
builder.AppendLine("    readonly request: ProtoDescriptor<TRequest>;");
builder.AppendLine("    readonly responseId: number;");
builder.AppendLine("    readonly response: ProtoDescriptor<TResponse>;");
builder.AppendLine("}");
builder.AppendLine();
builder.AppendLine("export interface EmptyRequest {");
builder.AppendLine("}");
builder.AppendLine();

foreach (var type in protoTypes)
{
    WriteInterface(builder, type);
}

foreach (var enumType in enums)
{
    WriteEnumObject(builder, enumType);
}

builder.AppendLine("export const Msg = {");
foreach (var entry in messages.OrderBy(entry => entry.Value).ThenBy(entry => entry.Key, StringComparer.Ordinal))
{
    builder.AppendLine($"    {entry.Key}: {entry.Value},");
}
builder.AppendLine("} as const;");
builder.AppendLine();

builder.AppendLine("export const Proto = {");
foreach (var type in protoTypes)
{
    var tsName = GetTypeScriptName(type);
    var runtimeName = GetPrimaryRuntimeName(type);
    builder.AppendLine($"    {tsName}: {{ name: \"{runtimeName}\" }} as ProtoDescriptor<{tsName}>,");
}
builder.AppendLine("} as const;");
builder.AppendLine();

builder.AppendLine("export const Routes = {");
foreach (var route in routes.OrderBy(route => route.Name, StringComparer.Ordinal))
{
    var requestTs = GetTypeScriptName(protoRuntimeNames[route.RequestProto]);
    var responseTs = GetTypeScriptName(protoRuntimeNames[route.ResponseProto]);
    builder.AppendLine($"    {route.Name}: {{");
    builder.AppendLine($"        requestId: Msg.{route.RequestMessage},");
    builder.AppendLine($"        request: Proto.{requestTs},");
    builder.AppendLine($"        responseId: Msg.{route.ResponseMessage},");
    builder.AppendLine($"        response: Proto.{responseTs}");
    builder.AppendLine($"    }} as GcRoute<{requestTs}, {responseTs}>,");
}
builder.AppendLine("} as const;");

Directory.CreateDirectory(Path.GetDirectoryName(outputFullPath)!);
File.WriteAllText(outputFullPath, builder.ToString(), new UTF8Encoding(false));
Console.WriteLine($"Generated {outputFullPath}");
Console.WriteLine($"Types: {protoTypes.Count}, enums: {enums.Count}, message IDs: {messages.Count}, routes: {routes.Count}");

static T? ReadJson<T>(string path)
{
    if (!File.Exists(path))
    {
        return default;
    }

    return JsonSerializer.Deserialize<T>(File.ReadAllText(path), new JsonSerializerOptions
    {
        PropertyNameCaseInsensitive = true,
        ReadCommentHandling = JsonCommentHandling.Skip,
        AllowTrailingCommas = true
    });
}

static IReadOnlyList<Type> GetLoadableTypes(Assembly assembly)
{
    try
    {
        return assembly.GetTypes();
    }
    catch (ReflectionTypeLoadException ex)
    {
        var types = ex.Types.Where(type => type != null).Cast<Type>().ToList();
        Console.Error.WriteLine(
            $"Warning: loaded {types.Count} types from {assembly.GetName().Name}; " +
            $"{ex.LoaderExceptions.Length} non-contract host types could not be resolved.");
        return types;
    }
}

static SortedDictionary<string, int> ReadMessageIds(IEnumerable<Type> enumTypes)
{
    var messages = new SortedDictionary<string, int>(StringComparer.Ordinal);
    foreach (var enumType in enumTypes)
    {
        foreach (var field in enumType.GetFields(BindingFlags.Public | BindingFlags.Static))
        {
            var rawName = GetProtoEnumName(field) ?? field.Name;
            var cleanName = ConvertMessageName(rawName);
            if (cleanName == null)
            {
                continue;
            }

            messages[cleanName] = Convert.ToInt32(field.GetRawConstantValue());
        }
    }

    return messages;
}

static void ValidateRoutes(
    IEnumerable<RouteDefinition> routes,
    IReadOnlyDictionary<string, int> messages,
    IReadOnlyDictionary<string, Type> protoRuntimeNames)
{
    foreach (var route in routes)
    {
        if (!messages.ContainsKey(route.RequestMessage))
        {
            throw new InvalidOperationException($"Route {route.Name} uses unknown request message '{route.RequestMessage}'.");
        }

        if (!messages.ContainsKey(route.ResponseMessage))
        {
            throw new InvalidOperationException($"Route {route.Name} uses unknown response message '{route.ResponseMessage}'.");
        }

        if (!protoRuntimeNames.ContainsKey(route.RequestProto))
        {
            throw new InvalidOperationException($"Route {route.Name} uses unknown request proto '{route.RequestProto}'.");
        }

        if (!protoRuntimeNames.ContainsKey(route.ResponseProto))
        {
            throw new InvalidOperationException($"Route {route.Name} uses unknown response proto '{route.ResponseProto}'.");
        }
    }
}

static void WriteInterface(StringBuilder builder, Type type)
{
    builder.AppendLine($"export interface {GetTypeScriptName(type)} {{");
    foreach (var property in GetProtoProperties(type))
    {
        var fieldName = GetFieldName(property);
        var fieldType = GetTypeScriptType(property.PropertyType);
        builder.AppendLine($"    readonly {fieldName}?: {fieldType};");
    }
    builder.AppendLine("}");
    builder.AppendLine();
}

static void WriteEnumObject(StringBuilder builder, Type enumType)
{
    builder.AppendLine($"export const {GetTypeScriptName(enumType)} = {{");
    foreach (var field in enumType.GetFields(BindingFlags.Public | BindingFlags.Static)
                 .OrderBy(field => Convert.ToInt64(field.GetRawConstantValue())))
    {
        var memberName = ConvertEnumMemberName(GetProtoEnumName(field) ?? field.Name, enumType);
        builder.AppendLine($"    {memberName}: {Convert.ToInt64(field.GetRawConstantValue())},");
    }
    builder.AppendLine("} as const;");
    builder.AppendLine();
}

static IEnumerable<PropertyInfo> GetProtoProperties(Type type)
{
    return type.GetProperties(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly)
        .Where(property => property.GetCustomAttributesData().Any(IsProtoMemberAttribute))
        .OrderBy(GetProtoMemberOrder);
}

static string GetFieldName(PropertyInfo property)
{
    var protoName = GetProtoMemberName(property);
    if (!string.IsNullOrWhiteSpace(protoName))
    {
        return SnakeToCamel(protoName);
    }

    return property.Name.Contains('_', StringComparison.Ordinal)
        ? SnakeToCamel(property.Name)
        : LowerFirst(property.Name);
}

static int GetProtoMemberOrder(PropertyInfo property)
{
    var attribute = property.GetCustomAttributesData().FirstOrDefault(IsProtoMemberAttribute);
    if (attribute == null || attribute.ConstructorArguments.Count == 0)
    {
        return int.MaxValue;
    }

    return Convert.ToInt32(attribute.ConstructorArguments[0].Value);
}

static string? GetProtoMemberName(PropertyInfo property)
{
    var attribute = property.GetCustomAttributesData().FirstOrDefault(IsProtoMemberAttribute);
    return attribute?.NamedArguments.FirstOrDefault(arg => arg.MemberName == "Name").TypedValue.Value as string;
}

static string? GetProtoEnumName(FieldInfo field)
{
    var attribute = field.GetCustomAttributesData().FirstOrDefault(IsProtoEnumAttribute);
    return attribute?.NamedArguments.FirstOrDefault(arg => arg.MemberName == "Name").TypedValue.Value as string;
}

static bool IsProtoContract(Type type)
{
    return type.GetCustomAttributesData().Any(attr => attr.AttributeType.Name == "ProtoContractAttribute");
}

static bool IsProtoMemberAttribute(CustomAttributeData attr)
{
    return attr.AttributeType.Name == "ProtoMemberAttribute";
}

static bool IsProtoEnumAttribute(CustomAttributeData attr)
{
    return attr.AttributeType.Name == "ProtoEnumAttribute";
}

static string GetTypeScriptType(Type type)
{
    type = Nullable.GetUnderlyingType(type) ?? type;

    if (type == typeof(bool))
    {
        return "boolean";
    }

    if (type == typeof(string))
    {
        return "string";
    }

    if (type == typeof(byte[]))
    {
        return "Uint8Array";
    }

    if (type == typeof(long) || type == typeof(ulong))
    {
        return "bigint";
    }

    if (type == typeof(byte) || type == typeof(sbyte) ||
        type == typeof(short) || type == typeof(ushort) ||
        type == typeof(int) || type == typeof(uint) ||
        type == typeof(float) || type == typeof(double) ||
        type == typeof(decimal))
    {
        return "number";
    }

    if (type.IsEnum)
    {
        return "number";
    }

    if (type.IsArray)
    {
        return $"{GetTypeScriptType(type.GetElementType()!)}[]";
    }

    if (type != typeof(string) && typeof(IEnumerable).IsAssignableFrom(type) && type.IsGenericType)
    {
        return $"{GetTypeScriptType(type.GetGenericArguments()[0])}[]";
    }

    return GetTypeScriptName(type);
}

static IEnumerable<string> GetRuntimeNames(Type type)
{
    yield return type.Name;

    var contractName = type.GetCustomAttributesData()
        .FirstOrDefault(attr => attr.AttributeType.Name == "ProtoContractAttribute")
        ?.NamedArguments
        .FirstOrDefault(arg => arg.MemberName == "Name")
        .TypedValue.Value as string;

    if (!string.IsNullOrWhiteSpace(contractName))
    {
        yield return contractName;
    }
}

static string GetPrimaryRuntimeName(Type type)
{
    return type.Name;
}

static string GetTypeScriptName(Type type)
{
    var names = new Stack<string>();
    for (var current = type; current != null; current = current.DeclaringType)
    {
        names.Push(SanitizeIdentifier(current.Name));
    }

    return string.Join("_", names);
}

static string ConvertEnumMemberName(string rawName, Type enumType)
{
    var cleaned = rawName;
    if (cleaned.StartsWith("k_e", StringComparison.Ordinal))
    {
        cleaned = cleaned[3..];
    }
    else if (cleaned.StartsWith("k_E", StringComparison.Ordinal))
    {
        cleaned = cleaned[3..];
    }
    else if (cleaned.StartsWith("k", StringComparison.Ordinal) && cleaned.Length > 1 && char.IsUpper(cleaned[1]))
    {
        cleaned = cleaned[1..];
    }

    var enumPrefix = enumType.Name + "_";
    if (cleaned.StartsWith(enumPrefix, StringComparison.Ordinal))
    {
        cleaned = cleaned[enumPrefix.Length..];
    }

    cleaned = SnakeToPascal(cleaned);
    return SanitizeIdentifier(cleaned);
}

static string? ConvertMessageName(string rawName)
{
    var cleaned = rawName;
    if (cleaned.StartsWith("k_EMsg", StringComparison.Ordinal))
    {
        cleaned = cleaned[6..];
    }
    else if (cleaned.StartsWith("kEMsg", StringComparison.Ordinal))
    {
        cleaned = cleaned[5..];
    }
    else
    {
        return null;
    }

    cleaned = cleaned.Replace("_", string.Empty);
    cleaned = cleaned.EndsWith("response", StringComparison.Ordinal)
        ? cleaned[..^8] + "Response"
        : cleaned;
    return SanitizeIdentifier(cleaned);
}

static string SanitizeIdentifier(string value)
{
    var builder = new StringBuilder(value.Length);
    foreach (var c in value)
    {
        builder.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
    }

    var result = builder.ToString();
    if (string.IsNullOrWhiteSpace(result))
    {
        return "Unknown";
    }

    if (char.IsDigit(result[0]))
    {
        result = "_" + result;
    }

    return result;
}

static string LowerFirst(string value)
{
    if (string.IsNullOrEmpty(value))
    {
        return value;
    }

    return char.ToLowerInvariant(value[0]) + value[1..];
}

static string SnakeToCamel(string value)
{
    var result = new StringBuilder(value.Length);
    var upperNext = false;
    foreach (var c in value)
    {
        if (c == '_')
        {
            upperNext = true;
            continue;
        }

        result.Append(upperNext ? char.ToUpperInvariant(c) : c);
        upperNext = false;
    }

    return result.ToString();
}

static string SnakeToPascal(string value)
{
    if (string.IsNullOrEmpty(value))
    {
        return value;
    }

    var parts = value
        .Split('_', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
        .Select(ToPascalToken);

    return string.Concat(parts);
}

static string ToPascalToken(string value)
{
    if (string.IsNullOrEmpty(value))
    {
        return value;
    }

    if (value.All(c => !char.IsLetter(c) || char.IsUpper(c)))
    {
        value = value.ToLowerInvariant();
    }

    return char.ToUpperInvariant(value[0]) + value[1..];
}

internal sealed class ContractLoadContext : AssemblyLoadContext
{
    private readonly AssemblyDependencyResolver _resolver;

    public ContractLoadContext(string assemblyPath)
        : base(isCollectible: false)
    {
        _resolver = new AssemblyDependencyResolver(assemblyPath);
    }

    protected override Assembly? Load(AssemblyName assemblyName)
    {
        var assemblyPath = _resolver.ResolveAssemblyToPath(assemblyName);
        return assemblyPath == null ? null : LoadFromAssemblyPath(assemblyPath);
    }
}

internal sealed record RouteDefinition(
    string Name,
    string RequestMessage,
    string RequestProto,
    string ResponseMessage,
    string ResponseProto);

internal sealed record Options(
    string AssemblyPath,
    string OutputPath,
    string ExtraMessageIdsPath,
    string RoutesPath)
{
    public static Options Parse(string[] args)
    {
        var values = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        for (var i = 0; i < args.Length; i++)
        {
            if (!args[i].StartsWith("--", StringComparison.Ordinal))
            {
                continue;
            }

            if (i + 1 >= args.Length)
            {
                throw new ArgumentException($"Missing value for {args[i]}");
            }

            values[args[i][2..]] = args[++i];
        }

        return new Options(
            Require(values, "assembly"),
            Require(values, "output"),
            Require(values, "extra-message-ids"),
            Require(values, "routes"));
    }

    private static string Require(IReadOnlyDictionary<string, string> values, string key)
    {
        return values.TryGetValue(key, out var value)
            ? value
            : throw new ArgumentException($"Missing --{key}");
    }
}
