// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SKYNET_server.Persistence;

#nullable disable

namespace SKYNET_server.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260715124238_AppStateAndIndexes")]
    partial class AppStateAndIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("SKYNET_server.Persistence.Entities.AchievementRecord", b =>
                {
                    b.Property<long>("SteamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Earned")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("MaxProgress")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Progress")
                        .HasColumnType("INTEGER");

                    b.HasKey("SteamId", "Name");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("SKYNET_server.Persistence.Entities.AppStateRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ActiveWebSteamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppState");
                });

            modelBuilder.Entity("SKYNET_server.Persistence.Entities.AvatarRecord", b =>
                {
                    b.Property<long>("SteamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("SteamId");

                    b.ToTable("Avatars");
                });

            modelBuilder.Entity("SKYNET_server.Persistence.Entities.CosmeticSettingsRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DotaPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("EquipmentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastImportAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastImportStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CosmeticSettings");
                });

            modelBuilder.Entity("SKYNET_server.Persistence.Entities.DotaEquipmentRecord", b =>
                {
                    b.Property<long>("SteamId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("SlotId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("DefIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeroName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("Style")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("SteamId", "HeroId", "SlotId");

                    b.ToTable("DotaEquipment");
                });

            modelBuilder.Entity("SKYNET_server.Persistence.Entities.DotaHeroIdRecord", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<uint>("HeroId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("DotaHeroIds");
                });

            modelBuilder.Entity("SKYNET_server.Persistence.Entities.DotaHeroSlotRecord", b =>
                {
                    b.Property<string>("HeroName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SlotName")
                        .HasColumnType("TEXT");

                    b.Property<uint>("SlotId")
                        .HasColumnType("INTEGER");

                    b.HasKey("HeroName", "SlotName");

                    b.ToTable("DotaHeroSlots");
                });

            modelBuilder.Entity("SKYNET_server.Persistence.Entities.DotaItemRecord", b =>
                {
                    b.Property<uint>("DefIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeroIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroNames")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageInventory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBundle")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTool")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prefab")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("QualityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("RarityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DefIndex");

                    b.ToTable("DotaItems");
                });

            modelBuilder.Entity("SKYNET_server.Persistence.Entities.DotaMatchPlayerRecord", b =>
                {
                    b.Property<long>("LobbyId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SteamId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("CoachTeam")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersonaName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("Slot")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Team")
                        .HasColumnType("INTEGER");

                    b.HasKey("LobbyId", "SteamId");

                    b.HasIndex("SteamId");

                    b.ToTable("DotaMatchPlayers");
                });

            modelBuilder.Entity("SKYNET_server.Persistence.Entities.DotaMatchRecord", b =>
                {
                    b.Property<long>("LobbyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Connect")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Dedicated")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("GameStartTime")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("GameState")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ServerSteamId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("State")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("LobbyId");

                    b.ToTable("DotaMatches");
                });

            modelBuilder.Entity("SKYNET_server.Persistence.Entities.FriendEdge", b =>
                {
                    b.Property<long>("SteamId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FriendSteamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SteamId", "FriendSteamId");

                    b.ToTable("Friends");
                });

            modelBuilder.Entity("SKYNET_server.Persistence.Entities.FriendRequestRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("FromSteamId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ToSteamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FromSteamId");

                    b.HasIndex("ToSteamId");

                    b.ToTable("FriendRequests");
                });

            modelBuilder.Entity("SKYNET_server.Persistence.Entities.GameServerRecord", b =>
                {
                    b.Property<long>("SteamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AppId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BotPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Dedicated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("Flags")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GameTags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("IP")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyValues")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MapName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModDir")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PasswordProtected")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QueryPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Secure")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("SpectatorPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpectatorServerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VersionString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SteamId");

                    b.ToTable("GameServers");
                });

            modelBuilder.Entity("SKYNET_server.Persistence.Entities.LobbyRecord", b =>
                {
                    b.Property<long>("SteamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AppId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameServer")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Joinable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LobbyData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LobbyType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Members")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("OwnerSteamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SteamId");

                    b.ToTable("Lobbies");
                });

            modelBuilder.Entity("SKYNET_server.Persistence.Entities.RemoteFileRecord", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.ToTable("RemoteFiles");
                });

            modelBuilder.Entity("SKYNET_server.Persistence.Entities.StatRecord", b =>
                {
                    b.Property<long>("SteamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<uint>("Data")
                        .HasColumnType("INTEGER");

                    b.HasKey("SteamId", "Name");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("SKYNET_server.Persistence.Entities.UserRecord", b =>
                {
                    b.Property<long>("SteamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AppId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersonaName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("SteamId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SKYNET_server.Persistence.Entities.WebAccountRecord", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SteamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Username");

                    b.HasIndex("SteamId");

                    b.ToTable("WebAccounts");
                });

            modelBuilder.Entity("SKYNET_server.Persistence.Entities.WebSessionRecord", b =>
                {
                    b.Property<string>("AccessToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientInstanceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Persistent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteIp")
                        .HasColumnType("TEXT");

                    b.Property<long>("SteamId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WebSession")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccessToken");

                    b.HasIndex("SteamId");

                    b.ToTable("WebSessions");
                });

            modelBuilder.Entity("SKYNET_server.Persistence.Entities.DotaMatchPlayerRecord", b =>
                {
                    b.HasOne("SKYNET_server.Persistence.Entities.DotaMatchRecord", "Match")
                        .WithMany("Players")
                        .HasForeignKey("LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("SKYNET_server.Persistence.Entities.DotaMatchRecord", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
