using System.Collections;
using System.Reflection;
using System.Runtime.Loader;
using System.Text;
using System.Text.Json;

var options = Options.Parse(args);
var assemblyFullPath = Path.GetFullPath(options.AssemblyPath);
var outputFullPath = Path.GetFullPath(options.OutputPath);
var appRootFullPath = Path.GetFullPath(options.AppRootPath);
var manifestFullPath = Path.GetFullPath(options.ManifestPath);
var extraIds = ReadJson<Dictionary<string, int>>(options.ExtraMessageIdsPath) ?? new Dictionary<string, int>();
var routes = ReadJson<List<RouteDefinition>>(options.RoutesPath) ?? new List<RouteDefinition>();
var manifest = ReadJson<AppManifest>(manifestFullPath) ?? new AppManifest();

var loadContext = new ContractLoadContext(assemblyFullPath);
var defaultAssembly = loadContext.LoadFromAssemblyPath(assemblyFullPath);
var loadableTypes = LoadContractTypes(options, appRootFullPath, manifest, loadContext, defaultAssembly)
    .ToList();

var protoTypes = loadableTypes
    .Where(IsProtoContract)
    .Where(type => !type.IsEnum)
    .Where(type => type.FullName?.StartsWith("Google.Protobuf.", StringComparison.Ordinal) != true)
    .OrderBy(GetTypeScriptName, StringComparer.Ordinal)
    .ToList();

var protoRuntimeNames = BuildRuntimeNameIndex(protoTypes);

var enums = loadableTypes
    .Where(IsProtoContract)
    .Where(type => type.IsEnum)
    .Where(type => type.FullName?.StartsWith("Google.Protobuf.", StringComparison.Ordinal) != true)
    .OrderBy(GetTypeScriptName, StringComparer.Ordinal)
    .ToList();

var messages = ReadMessageIds(enums);
foreach (var (name, value) in extraIds)
{
    messages[name] = value;
}

ValidateRoutes(routes, messages, protoRuntimeNames);

var builder = new StringBuilder();
builder.AppendLine("// <auto-generated>");
builder.AppendLine($"// Generated by {options.GeneratorPath} for GC app {options.AppId}.");
builder.AppendLine("// Source inputs: app manifest protobuf contracts, extra message ids, and route definitions.");
builder.AppendLine("// Do not edit this file directly.");
builder.AppendLine("// </auto-generated>");
builder.AppendLine();
builder.AppendLine("export interface ProtoDescriptor<TMessage> {");
builder.AppendLine("    readonly name: string;");
builder.AppendLine("}");
builder.AppendLine();
builder.AppendLine("export interface GcRoute<TRequest, TResponse> {");
builder.AppendLine("    readonly requestId: number;");
builder.AppendLine("    readonly request: ProtoDescriptor<TRequest>;");
builder.AppendLine("    readonly responseId: number;");
builder.AppendLine("    readonly response: ProtoDescriptor<TResponse>;");
builder.AppendLine("}");
builder.AppendLine();
builder.AppendLine("export interface EmptyRequest {");
builder.AppendLine("}");
builder.AppendLine();
builder.AppendLine("export type MessageId = number;");
builder.AppendLine();

foreach (var type in protoTypes)
{
    WriteInterface(builder, type);
}

foreach (var enumType in enums)
{
    WriteEnumObject(builder, enumType);
}

builder.AppendLine("export const Msg: {");
foreach (var entry in messages.OrderBy(entry => entry.Value).ThenBy(entry => entry.Key, StringComparer.Ordinal))
{
    builder.AppendLine($"    {entry.Key}: MessageId;");
}
builder.AppendLine("} = {");
foreach (var entry in messages.OrderBy(entry => entry.Value).ThenBy(entry => entry.Key, StringComparer.Ordinal))
{
    builder.AppendLine($"    {entry.Key}: {entry.Value},");
}
builder.AppendLine("};");
builder.AppendLine();

builder.AppendLine("export const Proto = {");
foreach (var type in protoTypes)
{
    var tsName = GetTypeScriptName(type);
    var runtimeName = GetPrimaryRuntimeName(type);
    builder.AppendLine($"    {tsName}: {{ name: \"{runtimeName}\" }} as ProtoDescriptor<{tsName}>,");
}
builder.AppendLine("} as const;");
builder.AppendLine();

builder.AppendLine("export const Routes = {");
foreach (var route in routes.OrderBy(route => route.Name, StringComparer.Ordinal))
{
    var requestTs = GetTypeScriptName(ResolveRouteType(route, route.RequestProto, "request", protoRuntimeNames));
    var responseTs = GetTypeScriptName(ResolveRouteType(route, route.ResponseProto, "response", protoRuntimeNames));
    builder.AppendLine($"    {route.Name}: {{");
    builder.AppendLine($"        requestId: Msg.{route.RequestMessage},");
    builder.AppendLine($"        request: Proto.{requestTs},");
    builder.AppendLine($"        responseId: Msg.{route.ResponseMessage},");
    builder.AppendLine($"        response: Proto.{responseTs}");
    builder.AppendLine($"    }} as GcRoute<{requestTs}, {responseTs}>,");
}
builder.AppendLine("} as const;");

Directory.CreateDirectory(Path.GetDirectoryName(outputFullPath)!);
File.WriteAllText(outputFullPath, builder.ToString(), new UTF8Encoding(false));
Console.WriteLine($"Generated {outputFullPath}");
Console.WriteLine($"Types: {protoTypes.Count}, enums: {enums.Count}, message IDs: {messages.Count}, routes: {routes.Count}");

static T? ReadJson<T>(string path)
{
    if (!File.Exists(path))
    {
        return default;
    }

    return JsonSerializer.Deserialize<T>(File.ReadAllText(path), new JsonSerializerOptions
    {
        PropertyNameCaseInsensitive = true,
        ReadCommentHandling = JsonCommentHandling.Skip,
        AllowTrailingCommas = true
    });
}

static IEnumerable<Type> LoadContractTypes(
    Options options,
    string appRootFullPath,
    AppManifest manifest,
    ContractLoadContext defaultLoadContext,
    Assembly defaultAssembly)
{
    var sources = manifest.ProtoContracts?.Sources;
    if (sources == null || sources.Count == 0)
    {
        sources = new List<ContractSource> { new() };
    }

    var loadedAssemblies = new Dictionary<string, Assembly>(StringComparer.OrdinalIgnoreCase)
    {
        [Path.GetFullPath(options.AssemblyPath)] = defaultAssembly
    };

    foreach (var source in sources)
    {
        NormalizeSource(source);
        var assembly = ResolveContractAssembly(options, appRootFullPath, source, defaultLoadContext, defaultAssembly, loadedAssemblies);
        foreach (var type in GetLoadableTypes(assembly).Where(type => MatchesSource(type, source)))
        {
            yield return type;
        }
    }
}

static Assembly ResolveContractAssembly(
    Options options,
    string appRootFullPath,
    ContractSource source,
    ContractLoadContext defaultLoadContext,
    Assembly defaultAssembly,
    IDictionary<string, Assembly> loadedAssemblies)
{
    var assembly = source.Assembly?.Trim();
    if (string.IsNullOrWhiteSpace(assembly)
        || string.Equals(assembly, "server", StringComparison.OrdinalIgnoreCase)
        || string.Equals(assembly, "default", StringComparison.OrdinalIgnoreCase)
        || string.Equals(assembly, defaultAssembly.GetName().Name, StringComparison.OrdinalIgnoreCase))
    {
        return defaultAssembly;
    }

    var candidatePath = Path.IsPathRooted(assembly)
        ? assembly
        : Path.Combine(appRootFullPath, assembly);
    if (File.Exists(candidatePath))
    {
        var fullPath = Path.GetFullPath(candidatePath);
        if (!loadedAssemblies.TryGetValue(fullPath, out var loaded))
        {
            loaded = defaultLoadContext.LoadFromAssemblyPath(fullPath);
            loadedAssemblies[fullPath] = loaded;
        }

        return loaded;
    }

    return Assembly.Load(new AssemblyName(assembly));
}

static void NormalizeSource(ContractSource source)
{
    source.TypeNames ??= new List<string>();
    source.TypeNamePrefixes ??= new List<string>();
    source.ContractNamePrefixes ??= new List<string>();
}

static bool MatchesSource(Type type, ContractSource source)
{
    var aliases = GetTypeAliases(type).ToList();
    return MatchesExactFilter(aliases, source.TypeNames)
        && MatchesPrefixFilter(aliases, source.TypeNamePrefixes)
        && MatchesPrefixFilter(GetContractNames(type), source.ContractNamePrefixes);
}

static bool MatchesExactFilter(IReadOnlyList<string> aliases, IReadOnlyList<string> filters)
{
    return filters.Count == 0 || aliases.Any(alias => filters.Contains(alias, StringComparer.Ordinal));
}

static bool MatchesPrefixFilter(IEnumerable<string> aliases, IReadOnlyList<string> prefixes)
{
    return prefixes.Count == 0 || aliases.Any(alias => prefixes.Any(prefix => alias.StartsWith(prefix, StringComparison.Ordinal)));
}

static IReadOnlyList<Type> GetLoadableTypes(Assembly assembly)
{
    try
    {
        return assembly.GetTypes();
    }
    catch (ReflectionTypeLoadException ex)
    {
        var types = ex.Types.Where(type => type != null).Cast<Type>().ToList();
        Console.Error.WriteLine(
            $"Warning: loaded {types.Count} types from {assembly.GetName().Name}; " +
            $"{ex.LoaderExceptions.Length} non-contract host types could not be resolved.");
        return types;
    }
}

static SortedDictionary<string, int> ReadMessageIds(IEnumerable<Type> enumTypes)
{
    var messages = new SortedDictionary<string, int>(StringComparer.Ordinal);
    foreach (var enumType in enumTypes)
    {
        foreach (var field in enumType.GetFields(BindingFlags.Public | BindingFlags.Static))
        {
            var rawName = GetProtoEnumName(field) ?? field.Name;
            var cleanName = ConvertMessageName(rawName);
            if (cleanName == null)
            {
                continue;
            }

            messages[cleanName] = Convert.ToInt32(field.GetRawConstantValue());
        }
    }

    return messages;
}

static void ValidateRoutes(
    IEnumerable<RouteDefinition> routes,
    IReadOnlyDictionary<string, int> messages,
    RuntimeNameIndex protoRuntimeNames)
{
    foreach (var route in routes)
    {
        if (!messages.ContainsKey(route.RequestMessage))
        {
            throw new InvalidOperationException($"Route {route.Name} uses unknown request message '{route.RequestMessage}'.");
        }

        if (!messages.ContainsKey(route.ResponseMessage))
        {
            throw new InvalidOperationException($"Route {route.Name} uses unknown response message '{route.ResponseMessage}'.");
        }

        ResolveRouteType(route, route.RequestProto, "request", protoRuntimeNames);
        ResolveRouteType(route, route.ResponseProto, "response", protoRuntimeNames);
    }
}

static RuntimeNameIndex BuildRuntimeNameIndex(IEnumerable<Type> protoTypes)
{
    var groupedNames = protoTypes
        .SelectMany(type => GetRuntimeNames(type).Select(name => (name, type)))
        .GroupBy(entry => entry.name, StringComparer.Ordinal)
        .ToList();

    var unique = new Dictionary<string, Type>(StringComparer.Ordinal);
    var ambiguous = new Dictionary<string, IReadOnlyList<Type>>(StringComparer.Ordinal);
    foreach (var group in groupedNames)
    {
        var candidates = group
            .Select(entry => entry.type)
            .Distinct()
            .OrderBy(GetCanonicalRuntimeName, StringComparer.Ordinal)
            .ToList();
        if (candidates.Count == 1)
        {
            unique[group.Key] = candidates[0];
            continue;
        }

        ambiguous[group.Key] = candidates;
    }

    return new RuntimeNameIndex(unique, ambiguous);
}

static Type ResolveRouteType(
    RouteDefinition route,
    string runtimeName,
    string routeSide,
    RuntimeNameIndex runtimeNames)
{
    if (runtimeNames.Unique.TryGetValue(runtimeName, out var type))
    {
        return type;
    }

    if (runtimeNames.Ambiguous.TryGetValue(runtimeName, out var candidates))
    {
        var examples = string.Join(", ", candidates.Take(6).Select(GetCanonicalRuntimeName));
        throw new InvalidOperationException(
            $"Route {route.Name} uses ambiguous {routeSide} proto '{runtimeName}'. " +
            $"Use a canonical runtime name. Candidates: {examples}");
    }

    throw new InvalidOperationException($"Route {route.Name} uses unknown {routeSide} proto '{runtimeName}'.");
}

static void WriteInterface(StringBuilder builder, Type type)
{
    builder.AppendLine($"export interface {GetTypeScriptName(type)} {{");
    foreach (var property in GetProtoProperties(type))
    {
        var fieldName = GetFieldName(property);
        var fieldType = GetTypeScriptType(property.PropertyType);
        builder.AppendLine($"    readonly {fieldName}?: {fieldType};");
    }
    builder.AppendLine("}");
    builder.AppendLine();
}

static void WriteEnumObject(StringBuilder builder, Type enumType)
{
    builder.AppendLine($"export const {GetTypeScriptName(enumType)} = {{");
    foreach (var field in enumType.GetFields(BindingFlags.Public | BindingFlags.Static)
                 .OrderBy(field => Convert.ToInt64(field.GetRawConstantValue())))
    {
        var memberName = ConvertEnumMemberName(GetProtoEnumName(field) ?? field.Name, enumType);
        builder.AppendLine($"    {memberName}: {Convert.ToInt64(field.GetRawConstantValue())},");
    }
    builder.AppendLine("} as const;");
    builder.AppendLine();
}

static IEnumerable<PropertyInfo> GetProtoProperties(Type type)
{
    return type.GetProperties(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly)
        .Where(property => property.GetCustomAttributesData().Any(IsProtoMemberAttribute))
        .OrderBy(GetProtoMemberOrder);
}

static string GetFieldName(PropertyInfo property)
{
    var protoName = GetProtoMemberName(property);
    if (!string.IsNullOrWhiteSpace(protoName))
    {
        return SnakeToCamel(protoName);
    }

    return property.Name.Contains('_', StringComparison.Ordinal)
        ? SnakeToCamel(property.Name)
        : LowerFirst(property.Name);
}

static int GetProtoMemberOrder(PropertyInfo property)
{
    var attribute = property.GetCustomAttributesData().FirstOrDefault(IsProtoMemberAttribute);
    if (attribute == null || attribute.ConstructorArguments.Count == 0)
    {
        return int.MaxValue;
    }

    return Convert.ToInt32(attribute.ConstructorArguments[0].Value);
}

static string? GetProtoMemberName(PropertyInfo property)
{
    var attribute = property.GetCustomAttributesData().FirstOrDefault(IsProtoMemberAttribute);
    return attribute?.NamedArguments.FirstOrDefault(arg => arg.MemberName == "Name").TypedValue.Value as string;
}

static string? GetProtoEnumName(FieldInfo field)
{
    var attribute = field.GetCustomAttributesData().FirstOrDefault(IsProtoEnumAttribute);
    return attribute?.NamedArguments.FirstOrDefault(arg => arg.MemberName == "Name").TypedValue.Value as string;
}

static bool IsProtoContract(Type type)
{
    return type.GetCustomAttributesData().Any(attr => attr.AttributeType.Name == "ProtoContractAttribute");
}

static bool IsProtoMemberAttribute(CustomAttributeData attr)
{
    return attr.AttributeType.Name == "ProtoMemberAttribute";
}

static bool IsProtoEnumAttribute(CustomAttributeData attr)
{
    return attr.AttributeType.Name == "ProtoEnumAttribute";
}

static string GetTypeScriptType(Type type)
{
    type = Nullable.GetUnderlyingType(type) ?? type;

    if (type == typeof(bool))
    {
        return "boolean";
    }

    if (type == typeof(string))
    {
        return "string";
    }

    if (type == typeof(byte[]))
    {
        return "Uint8Array";
    }

    if (type == typeof(long) || type == typeof(ulong))
    {
        return "bigint";
    }

    if (type == typeof(byte) || type == typeof(sbyte) ||
        type == typeof(short) || type == typeof(ushort) ||
        type == typeof(int) || type == typeof(uint) ||
        type == typeof(float) || type == typeof(double) ||
        type == typeof(decimal))
    {
        return "number";
    }

    if (type.IsEnum)
    {
        return "number";
    }

    if (type.IsArray)
    {
        return $"{GetTypeScriptType(type.GetElementType()!)}[]";
    }

    if (type != typeof(string) && typeof(IEnumerable).IsAssignableFrom(type) && type.IsGenericType)
    {
        return $"{GetTypeScriptType(type.GetGenericArguments()[0])}[]";
    }

    return GetTypeScriptName(type);
}

static IEnumerable<string> GetRuntimeNames(Type type)
{
    yield return GetCanonicalRuntimeName(type);

    var dottedCanonicalName = GetCanonicalRuntimeName(type).Replace('+', '.');
    if (!string.Equals(dottedCanonicalName, GetCanonicalRuntimeName(type), StringComparison.Ordinal))
    {
        yield return dottedCanonicalName;
    }

    yield return type.Name;

    foreach (var contractName in GetContractNames(type))
    {
        yield return contractName;
    }
}

static IEnumerable<string> GetTypeAliases(Type type)
{
    yield return GetCanonicalRuntimeName(type);
    yield return GetCanonicalRuntimeName(type).Replace('+', '.');
    yield return type.Name;
    if (!string.IsNullOrWhiteSpace(type.FullName))
    {
        yield return type.FullName!;
    }

    foreach (var contractName in GetContractNames(type))
    {
        yield return contractName;
    }
}

static string GetPrimaryRuntimeName(Type type)
{
    return GetCanonicalRuntimeName(type);
}

static IEnumerable<string> GetContractNames(Type type)
{
    var contractName = type.GetCustomAttributesData()
        .FirstOrDefault(attr => attr.AttributeType.Name == "ProtoContractAttribute")
        ?.NamedArguments
        .FirstOrDefault(arg => arg.MemberName == "Name")
        .TypedValue.Value as string;

    if (!string.IsNullOrWhiteSpace(contractName))
    {
        yield return contractName;
    }
}

static string GetCanonicalRuntimeName(Type type)
{
    return type.FullName ?? type.AssemblyQualifiedName ?? type.Name;
}

static string GetTypeScriptName(Type type)
{
    var names = new Stack<string>();
    for (var current = type; current != null; current = current.DeclaringType)
    {
        names.Push(SanitizeIdentifier(current.Name));
    }

    return string.Join("_", names);
}

static string ConvertEnumMemberName(string rawName, Type enumType)
{
    var cleaned = rawName;
    if (cleaned.StartsWith("k_e", StringComparison.Ordinal))
    {
        cleaned = cleaned[3..];
    }
    else if (cleaned.StartsWith("k_E", StringComparison.Ordinal))
    {
        cleaned = cleaned[3..];
    }
    else if (cleaned.StartsWith("k", StringComparison.Ordinal) && cleaned.Length > 1 && char.IsUpper(cleaned[1]))
    {
        cleaned = cleaned[1..];
    }

    var enumPrefix = enumType.Name + "_";
    if (cleaned.StartsWith(enumPrefix, StringComparison.Ordinal))
    {
        cleaned = cleaned[enumPrefix.Length..];
    }

    cleaned = SnakeToPascal(cleaned);
    return SanitizeIdentifier(cleaned);
}

static string? ConvertMessageName(string rawName)
{
    var cleaned = rawName;
    if (cleaned.StartsWith("k_EMsg", StringComparison.Ordinal))
    {
        cleaned = cleaned[6..];
    }
    else if (cleaned.StartsWith("kEMsg", StringComparison.Ordinal))
    {
        cleaned = cleaned[5..];
    }
    else
    {
        return null;
    }

    cleaned = cleaned.Replace("_", string.Empty);
    cleaned = cleaned.EndsWith("response", StringComparison.Ordinal)
        ? cleaned[..^8] + "Response"
        : cleaned;
    return SanitizeIdentifier(cleaned);
}

static string SanitizeIdentifier(string value)
{
    var builder = new StringBuilder(value.Length);
    foreach (var c in value)
    {
        builder.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
    }

    var result = builder.ToString();
    if (string.IsNullOrWhiteSpace(result))
    {
        return "Unknown";
    }

    if (char.IsDigit(result[0]))
    {
        result = "_" + result;
    }

    return result;
}

static string LowerFirst(string value)
{
    if (string.IsNullOrEmpty(value))
    {
        return value;
    }

    return char.ToLowerInvariant(value[0]) + value[1..];
}

static string SnakeToCamel(string value)
{
    var result = new StringBuilder(value.Length);
    var upperNext = false;
    foreach (var c in value)
    {
        if (c == '_')
        {
            upperNext = true;
            continue;
        }

        result.Append(upperNext ? char.ToUpperInvariant(c) : c);
        upperNext = false;
    }

    return result.ToString();
}

static string SnakeToPascal(string value)
{
    if (string.IsNullOrEmpty(value))
    {
        return value;
    }

    var parts = value
        .Split('_', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
        .Select(ToPascalToken);

    return string.Concat(parts);
}

static string ToPascalToken(string value)
{
    if (string.IsNullOrEmpty(value))
    {
        return value;
    }

    if (value.All(c => !char.IsLetter(c) || char.IsUpper(c)))
    {
        value = value.ToLowerInvariant();
    }

    return char.ToUpperInvariant(value[0]) + value[1..];
}

internal sealed class ContractLoadContext : AssemblyLoadContext
{
    private readonly AssemblyDependencyResolver _resolver;

    public ContractLoadContext(string assemblyPath)
        : base(isCollectible: false)
    {
        _resolver = new AssemblyDependencyResolver(assemblyPath);
    }

    protected override Assembly? Load(AssemblyName assemblyName)
    {
        var assemblyPath = _resolver.ResolveAssemblyToPath(assemblyName);
        return assemblyPath == null ? null : LoadFromAssemblyPath(assemblyPath);
    }
}

internal sealed record RouteDefinition(
    string Name,
    string RequestMessage,
    string RequestProto,
    string ResponseMessage,
    string ResponseProto);

internal sealed record RuntimeNameIndex(
    IReadOnlyDictionary<string, Type> Unique,
    IReadOnlyDictionary<string, IReadOnlyList<Type>> Ambiguous);

internal sealed class AppManifest
{
    public ProtoContractOptions? ProtoContracts { get; set; }
}

internal sealed class ProtoContractOptions
{
    public List<ContractSource>? Sources { get; set; }
}

internal sealed class ContractSource
{
    public string? Assembly { get; set; }
    public List<string> TypeNames { get; set; } = new();
    public List<string> TypeNamePrefixes { get; set; } = new();
    public List<string> ContractNamePrefixes { get; set; } = new();
}

internal sealed record Options(
    string AppId,
    string GeneratorPath,
    string AppRootPath,
    string ManifestPath,
    string AssemblyPath,
    string OutputPath,
    string ExtraMessageIdsPath,
    string RoutesPath)
{
    public static Options Parse(string[] args)
    {
        var values = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        for (var i = 0; i < args.Length; i++)
        {
            if (!args[i].StartsWith("--", StringComparison.Ordinal))
            {
                continue;
            }

            if (i + 1 >= args.Length)
            {
                throw new ArgumentException($"Missing value for {args[i]}");
            }

            values[args[i][2..]] = args[++i];
        }

        return new Options(
            values.GetValueOrDefault("app-id", "unknown"),
            values.GetValueOrDefault("generator", "GC/tools/generate-contracts.ps1"),
            values.GetValueOrDefault("app-root", "."),
            values.GetValueOrDefault("manifest", "gc.json"),
            Require(values, "assembly"),
            Require(values, "output"),
            Require(values, "extra-message-ids"),
            Require(values, "routes"));
    }

    private static string Require(IReadOnlyDictionary<string, string> values, string key)
    {
        return values.TryGetValue(key, out var value)
            ? value
            : throw new ArgumentException($"Missing --{key}");
    }
}
