using System;
using System.Runtime.InteropServices;

// Autogenerated @ 21/08/18
namespace InterfaceUser
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement CLIENTUSER_INTERFACE_VERSION001
    /// </summary>
    [Core.Interface.Delegate(Name = "CLIENTUSER_INTERFACE_VERSION001")]
    class CLIENTUSER_INTERFACE_VERSION001_Delegates
    {
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate int GetHSteamUser(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void LogOn(IntPtr _, ulong steamid);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void LogOnWithPassword(IntPtr _, string username, string password);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void LogOnAndCreateNewSteamAccountIfNeeded(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate uint LogOnConnectionless(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void LogOff(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool BLoggedOn(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate uint GetLogonState(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool BConnected(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool BTryingToLogon(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate ulong GetSteamId(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate ulong GetConsoleSteamId(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate ulong GetClientInstanceId(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool IsVACBanned(IntPtr _, uint game);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool SetEmail(IntPtr _, string new_email);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool SetConfigString(IntPtr _, uint config_sub_tree, string key, string value);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool GetConfigString(IntPtr _, uint config_sub_tree, string key, IntPtr value_out, int max_out);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool SetConfigInt(IntPtr _, uint config_sub_tree, string key, int new_value);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool GetConfigInt(IntPtr _, uint config_sub_tree, string key, ref int value);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool DeleteConfigKey(IntPtr _, uint config_sub_tree, string key);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool GetConfigStoreKeyName(IntPtr _, uint config_sub_tree, string key, IntPtr value_out, int max_out);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate int InitiateGameConnection(IntPtr _, IntPtr blob, uint blob_count, ulong gameserver_id, uint server_ip, short server_port, bool secure);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void InitiateGameConnectionOld(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void TerminateGameConnection(IntPtr _, uint server_ip, short server_port);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool TerminateAppMuliStep(IntPtr _, uint a, uint b);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void SetSelfAsPrimaryChatDestination(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool IsPrimaryChatDestination(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void RequestLegacyCDKey(IntPtr _, uint appid);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool AckGuestPass(IntPtr _, string passcode);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool RedeemGuestPass(IntPtr _, string passcode);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate uint GuestPassToGiveCount(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate uint GetGuestPassToRedeemCount(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool GetGuestPassToGiveInfo(IntPtr _, uint nPassIndex, ref uint pgidGuestPassID, ref uint pnPackageID, ref uint pRTime32Created, ref uint pRTime32Expiration, ref uint pRTime32Sent, ref uint pRTime32Redeemed, IntPtr pchRecipientAddress, int cRecipientAddressSize);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool GetGuestPassToGiveOut(IntPtr _, uint nPassIndex);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool GetGuestPassToRedeem(IntPtr _, uint nPassIndex);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool GetGuestPassToRedeemInfo(IntPtr _, uint nPassIndex, ref uint pgidGuestPassID, ref uint pnPackageID, ref uint pRTime32Created, ref uint pRTime32Expiration, ref uint pRTime32Sent, ref uint pRTime32Redeemed);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool GetGuestPassToRedeemSenderName(IntPtr _, uint nPassIndex, IntPtr pchSenderName, int cSenderNameSize);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate uint GetNumAppsInGuestPassesToRedeem(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate uint GetAppsInGuestPassesToRedeem(IntPtr _, IntPtr app_array_to_fill, int max_fill);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate uint GetCountUserNotifications(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate uint GetCountUserNotification(IntPtr _, uint type);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void RequestStoreAuthURL(IntPtr _, string a);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void SetLanguage(IntPtr _, string a);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void TrackAppUsageEvent(IntPtr _, ulong game_id, int usage_event, string extra_info);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate uint RaiseConnectionPriority(IntPtr _, uint new_priority);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void ResetConnectionPriority(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool BHasCachedCredentials(IntPtr _, string a);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool SetAccountNameForCachedCredentialLogin(IntPtr _, string name, bool a);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool GetCurrentWebAuthToken(IntPtr _, IntPtr out_string, int out_max);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate uint RequestWebAuthToken(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void SetLoginInformation(IntPtr _, string username, string password, bool remember_password);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void SetTwoFactorCode(IntPtr _, string code);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void ClearLoginInformation(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool GetLanguage(IntPtr _, IntPtr out_string, int out_max);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool BIsCyberCafe(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool BIsAcademicAccount(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool BIsPortal2EducationAccount(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool BIsAlienwareDemoAccount(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void CreateAccount(IntPtr _, string new_username, string new_password, string new_email);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate uint ResetPassword(IntPtr _, string account_name, string old_password, string new_password, string code, string answer);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void ValidatePasswordResetCodeAndSendSms(IntPtr _, string a, string b);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void TrackNatTraversalStat(IntPtr _, IntPtr stat_out);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void TrackSteamUsageEvent(IntPtr _, uint usage_event, string extra, uint a);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void TrackSteamGuiUsage(IntPtr _, string a);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void SetComputerInUse(IntPtr _);
    }
}
