using System;
using System.Runtime.InteropServices;

// Autogenerated @ 21/08/18
namespace InterfaceHTMLSurface
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamHTMLSurface004
    /// </summary>
    [Core.Interface.Delegate(Name = "SteamHTMLSurface004")]
    class SteamHTMLSurface004_Delegates
    {
    }
}
