using System;
using System.Runtime.InteropServices;

// Autogenerated @ 21/08/18
namespace InterfaceUserStats
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamUserStats011
    /// </summary>
    [Core.Interface.Delegate(Name = "SteamUserStats011")]
    class SteamUserStats011_Delegates
    {
    }
}
