using System;
using System.Runtime.InteropServices;

// Autogenerated @ 21/08/18
namespace InterfaceScreenshots
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamScreenshots003
    /// </summary>
    [Core.Interface.Delegate(Name = "SteamScreenshots003")]
    class SteamScreenshots003_Delegates
    {
    }
}
