using System;
using System.Runtime.InteropServices;

// Autogenerated @ 21/08/18
namespace IntefaceNetworking
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamNetworking005
    /// </summary>
    [Core.Interface.Delegate(Name = "SteamNetworking005")]
    class SteamNetworking005_Delegates
    {
    }
}
