using System;
using System.Runtime.InteropServices;

// Autogenerated @ 21/08/18
namespace InterfaceFriends
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamFriends015
    /// </summary>
    [Core.Interface.Delegate(Name = "SteamFriends015")]
    class SteamFriends015_Delegates
    {
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate string GetPersonaName(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate int SetPersonaName(IntPtr _, string name);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate uint GetPersonaState(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate int GetFriendCount(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate ulong GetFriendByIndex(IntPtr _, int index);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate uint GetFriendRelationship(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate uint GetFriendPersonaState(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate string GetFriendPersonaName(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool GetFriendGamePlayed(IntPtr _, ulong steam_id, IntPtr friend_game_info_out);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate string GetFriendPersonaNameHistory(IntPtr _, ulong steam_id, int index);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate int GetFriendSteamLevel(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate string GetPlayerNickname(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate int GetFriendsGroupCount(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate short GetGroupIdByIndex(IntPtr _, int index);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate string GetFriendsGroupName(IntPtr _, short id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate int GetFriendsGroupMembersCount(IntPtr _, short id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void GetFriendsGroupMembersList(IntPtr _, short id, ref IntPtr steam_id_out, int max_steam_id_out);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool HasFriend(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate int GetClanCount(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate ulong GetClanByIndex(IntPtr _, int index);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate string GetClanName(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate string GetClanTag(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool GetClanActivityCounts(IntPtr _, ulong steam_id, ref int online, ref int in_game, ref int chatting);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate int DownloadClanActivityCounts(IntPtr _, System.UInt64[] clans, int count);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate int GetFriendCountFromSource(IntPtr _, ulong source_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate ulong GetFriendFromSourceByIndex(IntPtr _, ulong source_id, int index);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool IsUserInSource(IntPtr _, ulong steam_id, ulong source_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void SetInGameVoiceSpeaking(IntPtr _, ulong steam_id, bool speaking);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void ActivateGameOverlay(IntPtr _, string dialog);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void ActiveGameOverlayToUser(IntPtr _, string dialog, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void ActiveGameOverlayToWebPage(IntPtr _, string url);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void ActivateGameOverlayToStore(IntPtr _, uint app_id, uint flag);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void SetPlayedWith(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void ActivateGameOverlayInviteDialog(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate int GetSmallFriendAvatar(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate int GetMediumFriendAvatar(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate int GetLargeFriendAvatar(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool RequestUserInformation(IntPtr _, ulong steam_id, bool require_name_only);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate int RequestClanOfficerList(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate ulong GetClanOwner(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate int GetClanOfficerCount(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate ulong GetClanOfficerByIndex(IntPtr _, ulong clan, int officer);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate uint GetUserRestrictions(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool SetRichPresence(IntPtr _, string key, string value);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool ClearRichPresence(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate string GetFriendRichPresence(IntPtr _, ulong steam_id, string key);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate int GetFriendRichPresenceKeyCount(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate string GetFriendRichPresenceKeyByIndex(IntPtr _, ulong steam_id, int key);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate void RequestFriendRichPresence(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool InviteUserToGame(IntPtr _, ulong steam_id, string connect);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate int GetCoplayFriendCount(IntPtr _);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate ulong GetCoplayFriend(IntPtr _, int index);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate int GetFriendCoplayTime(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate uint GetFriendCoplayGame(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate int JoinClanChatRoom(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool LeaveClanChatRoom(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate int GetClanChatMemberCount(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate ulong GetChatMemberByIndex(IntPtr _, ulong steam_id, int index);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool SendClanChatMessage(IntPtr _, ulong steam_id, string msg);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate int GetClanChatMessage(IntPtr _, ulong steam_id, int index, IntPtr text_out, int max_text, uint chat_type, ref ulong chater_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool IsClanChatAdmin(IntPtr _, ulong chat_id, ulong user_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool IsClanChatWindowOpenInSteam(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool OpenClanChatWindowInSteam(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool CloseClanChatWindowInSteam(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool SetListenForFriendsMessages(IntPtr _, bool intercept);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool ReplyToFriendMessage(IntPtr _, ulong steam_id, string msg);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate int GetFriendMessage(IntPtr _, ulong steam_id, int msg_index, IntPtr b_pointer, int b_length, ref uint msg_type);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate int GetFollowerCount(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate int IsFollowing(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate int EnumerateFollowingList(IntPtr _, uint starting_index);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool IsClanPublic(IntPtr _, ulong steam_id);
        [UnmanagedFunctionPointer(CallingConvention.ThisCall)]
        public delegate bool IsClanOfficialGameGroup(IntPtr _, ulong steam_id);
    }
}
