using System;
using System.Runtime.InteropServices;

// Autogenerated @ 21/08/18
namespace InterfaceUGC
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamUGC010
    /// </summary>
    [Core.Interface.Delegate(Name = "SteamUGC010")]
    class SteamUGC010_Delegates
    {
    }
}
