using System;
using System.Runtime.InteropServices;

// Autogenerated @ 21/08/18
namespace InterfaceHTTP
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamHTTP002
    /// </summary>
    [Core.Interface.Delegate(Name = "SteamHTTP002")]
    class SteamHTTP002_Delegates
    {
    }
}
