using System;
using System.Runtime.InteropServices;

// Autogenerated @ 21/08/18
namespace InterfaceGameServer
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamGameServer012
    /// </summary>
    [Core.Interface.Delegate(Name = "SteamGameServer012")]
    class SteamGameServer012_Delegates
    {
    }
}
