using System;
using System.Runtime.InteropServices;

// Autogenerated @ 21/08/18
namespace InterfaceUnifiedMessages
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamUnifiedMessages001
    /// </summary>
    [Core.Interface.Delegate(Name = "SteamUnifiedMessages001")]
    class SteamUnifiedMessages001_Delegates
    {
    }
}
