using System;
using System.Runtime.InteropServices;

// Autogenerated @ 21/08/18
namespace InterfaceRemoteStorage
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamRemoteStorage014
    /// </summary>
    [Core.Interface.Delegate(Name = "SteamRemoteStorage014")]
    class SteamRemoteStorage014_Delegates
    {
    }
}
