using System;
using System.Runtime.InteropServices;

// Autogenerated @ 21/08/18
namespace InterfaceMusicRemote
{
    /// <summary>
    /// Exports the delegates for all interfaces that implement SteamMusicRemote001
    /// </summary>
    [Core.Interface.Delegate(Name = "SteamMusicRemote001")]
    class SteamMusicRemote001_Delegates
    {
    }
}
